"use strict";
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
Object.defineProperty(exports, "__esModule", { value: true });
var application_1 = require("./application");
var hello_controller_1 = require("./hello_controller");
application_1.application.register("hello", hello_controller_1.default);
var react_controller_1 = require("./react_controller");
application_1.application.register("react", react_controller_1.default);
// Lazy load controllers as they appear in the DOM (remember not to preload controllers in import map!)
// import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
// lazyLoadControllersFrom("controllers", application)
